spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 0000
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create    # 개발 환경에서는 create, 운영 환경에서는 update 권장
    show-sql: true         # 개발 중에는 true, 운영 환경에서는 false
    format_sql : true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080