spring:
  profiles:
    active: local  # 기본적으로 local 프로필 사용

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true