spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      platform: h2
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

jwt:
  issuer: gamers_ranc
  secret: 6F4FD59C52C94953A2FDBD219F382C8DA2EE78B33569C83C87614F6C3E
  header: Authorization
  expiry_seconds: 3600
  refresh_expiry_seconds: 86400

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

blockchain:
  network:
    url: ${BLOCKCHAIN_NETWORK_URL:http://localhost:8545} # 로컬 Ganache나 테스트넷 URL
  contract:
    address: ${BLOCKCHAIN_CONTRACT_ADDRESS}
  keystore:
    path: ${BLOCKCHAIN_KEYSTORE_PATH}
    password: ${BLOCKCHAIN_KEYSTORE_PASSWORD}
