spring:
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always
      platform: h2
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

jwt:
  issuer: games_ranc
  secret: ${JWT_SECRET_KEY}
  header: Authorization
  token-validity-in-seconds: 86400

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

blockchain:
  network:
    url: ${BLOCKCHAIN_NETWORK_URL:http://localhost:8545} # 로컬 Ganache나 테스트넷 URL
  contract:
    address: ${BLOCKCHAIN_CONTRACT_ADDRESS}
  keystore:
    path: ${BLOCKCHAIN_KEYSTORE_PATH}
    password: ${BLOCKCHAIN_KEYSTORE_PASSWORD}
