spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/gamers_ranc?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&useSSL=false
    username: root
    password: ddgh930810
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: false
      path: /h2-console
      settings:
        web-allow-others: true

server:
  port: 80

springdoc:
  swagger-ui:
    path: /swagger